# Project information
site_name: Cheatsheets
site_author: ivansaul
site_url: https://ivansaul.github.io/cheatsheets

# Repository
repo_name: ivansaul/cheatsheets
repo_url: https://github.com/ivansaul/cheatsheets

# Copyright
copyright: Copyright &copy; 2025 ivansaul

# Configuration
theme:
  name: material
  custom_dir: ../../material/overrides
  language: en
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - content.action.edit
  icon:
    annotation: material/plus-circle
    repo: fontawesome/brands/github
    edit: fontawesome/regular/pen-to-square
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to system preference

# Extensions
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.blocks.caption
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - material/overrides/.icons
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true

# Plugins
plugins:
  - meta
  - search
  - macros:
      module_name: ../../macros
  - social:
      enabled: !ENV [CI, false]
      cards_layout: default/accent
      cards_layout_options:
        font_family: Roboto
        background_color: "#0083e7"
  - glightbox:
      zoomable: false
      draggable: true
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - literate-nav:
      nav_file: .toc.md
  - git-committers:
      repository: ivansaul/cheatsheets
      branch: master
      docs_path: src/en/docs/
      enabled: !ENV [CI, false]

# Extras
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/tDvybtJ7y9
    - icon: fontawesome/brands/github
      link: https://github.com/ivansaul/cheatsheets
  analytics:
    provider: google
    property: G-MZBYC91Y7Z
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback!
  alternate:
    - name: English
      link: https://ivansaul.github.io/cheatsheets
      lang: en
